---
- name: Rollback Red Hat OS
  hosts: your_target_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Stop packagekit service
      service:
        name: packagekit
        state: stopped

    - name: Rollback using dnf history
      ansible.posix.dnf:
        name: '*'
        state: latest
        disable_gpg_check: yes
        disable_excludes: main,updates
        skip_broken: yes
        list_only: yes
      register: dnf_rollback_result

    - name: Revert packages
      ansible.posix.dnf:
        name: "{{ item.name }}"
        state: present
      loop: "{{ dnf_rollback_result.results }}"
      when: item.state == "removed"

    - name: Check if rollback was successful
      debug:
        msg: "Rollback successful"
      when: dnf_rollback_result.changed
