---
- name: Rollback RHEL Server
  hosts: your_target_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Stop packagekit service
      service:
        name: packagekit
        state: stopped
        enabled: no

    - name: Rollback using yum history
      yum:
        name: '*'
        state: latest
        disable_gpg_check: yes
        exclude: kernel*
      register: yum_rollback_result

    - name: Revert packages
      yum:
        name: "{{ item.name }}"
        state: present
        disable_gpg_check: yes
      loop: "{{ yum_rollback_result.results | selectattr('state', 'equalto', 'absent') | list }}"
      when: yum_rollback_result.changed

    - name: Check if rollback was successful
      debug:
        msg: "Rollback successful"
      when: yum_rollback_result.changed
